  
  CREATE TABLE `aicrud`.`book` (
  `BookID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Author` VARCHAR(100) NULL DEFAULT NULL,
  `AvailableCopies` INT(11) NULL DEFAULT NULL,
  `Active` TINYINT(1) NULL DEFAULT 0,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedAt` DATE NULL DEFAULT NULL,
  `ModifiedBy` VARCHAR(45) NULL DEFAULT NULL,
  `ModifiedAt` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`BookID`));
  
  
  
  CREATE TABLE `aicrud`.`users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `LibraryID` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  `ContactNo` VARCHAR(45) NULL DEFAULT NULL
  `Active` TINYINT(1) NULL DEFAULT 0,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedAt` DATE NULL DEFAULT NULL,
  `ModifiedBy` VARCHAR(45) NULL DEFAULT NULL,
  `ModifiedAt` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `LibraryID_UNIQUE` (`LibraryID` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE);
  
  

CREATE TABLE `aicrud`.`borrowbook` (
  `BorrowID` INT NOT NULL AUTO_INCREMENT,
  `BookID` INT(11) NOT NULL,
  `UserID` INT(11) NOT NULL,
  `BorrowDate` DATE NULL DEFAULT NULL,
  `DueDate` DATE NULL DEFAULT NULL,
  `ReturnDate` DATE NULL DEFAULT NULL,
  `LateFee` DECIMAL(10,2) NULL DEFAULT NULL,
  `Active` TINYINT(1) NULL DEFAULT 0,
  `CreatedBy` VARCHAR(45) NULL DEFAULT NULL,
  `CreatedAt` DATE NULL DEFAULT NULL,
  `ModifiedBy` VARCHAR(45) NULL DEFAULT NULL,
  `ModifiedAt` DATE NULL,
  PRIMARY KEY (`BorrowID`),
  INDEX `BookID_idx` (`BookID` ASC) VISIBLE,
  INDEX `UserID_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `BookID`
    FOREIGN KEY (`BookID`)
    REFERENCES `aicrud`.`book` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `aicrud`.`users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
